### ISSUE TITLE
请问submission中的actions1255.npy是如何得到的？

### ISSUE THREAD

**Issue by vickhardy** [AsprinChina/L2RPN_NIPS_2020_a_PPO_Solution#1]
训练过程中没有提到，请问它是如何得到的，作用是什么

**Comment by Aspirin96** [comment]
### Question
> What is the `actions1255.npy` in the submission folder, how is it obtained, and what is its function?

### Answer
Thanks for your question.  
* What is it?
Similar to `actions208.npy`, `actions1255.npy` is also a file in numpy format (2D matrix) recording 1255 actions: it has 1255 rows and 494 columns, and each row is corresponding to a selected action.
* How is it obtained?
As we introduced, the 208 actions in `actions208.npy` are obtained by filtering out some actions that occur less frequently (<10 times). The 1255 actions in `actions1255.npy` are obtained in a similar manner, but with a smaller threshold (<5 times maybe).
* What is its function?
We hope a larger search space for the agent may improve its performance, so we search from 1255 actions rather than 208 actions when the power grid is in danger. However, we find it not really helpful in the end. Therefore, we didn't give it an introduction. In fact, you can ignore this file and comment out the relevant codes.

**Comment by vickhardy** [comment]
Thanks for your answer! It helps me a lot.
